### PR TITLE
feat(): draft schema migration update

### PR DESCRIPTION
**Pull request by juliannaeapicella**
1. Description: Updates upgradeDraftSchema to use most recent migration.

1. Instructions for testing:

1. Closes Issues: #5935

1. [x] used semantic commit messages
  
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release automation will not run!)

1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the release instructions for more details.

### CODE REVIEW

**Comment by juliannaeapicella** [comment]
@sonofflynn89 @mjuniper migrateFeedConfig was also not being run on drafts. Should we add it to this migration function?

**Comment by sonofflynn89** [comment]
@juliannaeapicella the migrate feed config function was introduced over a year ago as we switched to a new format for storing the DCAT configs. I don't know that we would have any drafts out in the wild that _would_ have the old config, but I guess we could call the function in here just to be safe.

**Review by rweber-esri — APPROVED** [review]
One comment about verifying the new migration spies are called. Otherwise looks good to me.

**Comment by rweber-esri** [comment]
> @juliannaeapicella the migrate feed config function was introduced over a year ago as we switched to a new format for storing the DCAT configs. I don't know that we would have any drafts out in the wild that _would_ have the old config, but I guess we could call the function in here just to be safe.

Thanks for verifying @sonofflynn89

**Pull request merged**
