### PR TITLE
feat: add disableDiscussions capability

### PR DESCRIPTION
**Pull request by MikeTschudi**
1. Description:
  * Add disableDiscussions capability to Hub site 
  * Fix minor typo in README

1. Instructions for testing:

Not yet testable

1. Closes Issues: #<number> (if appropriate)

1. [x] used semantic commit messages
  
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release automation will not run!)

1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the release instructions for more details.

### CODE REVIEW

**Comment by dbouwman** [comment]
@rweber-esri what is the impact of setting `discussionsDisabled` on a site's capabilities? Does that just mean it needs to be manually enabled? or does this make it so that discussions are not available at all?

**Comment by rweber-esri** [comment]
@dbouwman @MikeTschudi 

> @rweber-esri what is the impact of setting discussionsDisabled on a site's capabilities? Does that just mean it needs to be manually enabled? or does this make it so that discussions are not available at all?

Discussions are enabled by default for Hub Premium sites, meaning `discussionsDisabled` is _not_ present in the capabilities array/hash. This capability maps to a slider widget in Hub's site-settings editor UI. When the capability is absent, the slider is enabled, meaning discussions is enabled. If a site editor toggles the slider to disabled and saves the site settings, it adds `discussionsDisabled` capability to the array/hash.

**Comment by MikeTschudi** [comment]
Thank you, @rweber-esri; I added the capability to too many places.

Would reverting all but `ensure-require-site-properties.ts` be acceptable?  (It's the `deepSet` call at the end of `ensureRequiredSiteProperties` that is removing the "disableDiscussions" capability during site creation.)

**Comment by rweber-esri** [comment]
> Would reverting all but `ensure-require-site-properties.ts` be acceptable? (It's the `deepSet` call at the end of `ensureRequiredSiteProperties` that is removing the "disableDiscussions" capability during site creation.)

I'm not sure that's desirable, as that would disable discussions for all newly created sites when we want discussions to be _enabled_ by default. I'm curious if you could elaborate on your use case? Does this pertain to cloning an existing site which has discussions disabled and wanting to persist that setting through to the clone?

**Comment by MikeTschudi** [comment]
Thank you, @rweber-esri, that, indeed does the trick.

I created the following test; it failed. I added your code; it worked.  I propose closing this PR and submitting a new one with your code and this test.
```
  it("keeps capabilities in model while ensuring default capabilities", function () {
    const model = {
      item: {},
      data: {
        values: {
          subdomain: "name-org",
          defaultHostname: "name-org.hub.arcgis.com",
          capabilities: [
            "my_data",
            "disableDiscussions",
          ]
        },
      },
    } as unknown as IModel;

    const chk = ensureRequiredSiteProperties(model, "vader");
    expect(chk.data.values.capabilities).toContain("my_data");
    expect(chk.data.values.capabilities).toContain("disableDiscussions");
  });
```

**Pull request closed without merging**
