### PR TITLE
chore: update fast-xml-parser

### PR DESCRIPTION
**Pull request by MikeTschudi**
1. Description:
[xml2js is vulnerable to prototype pollution](https://github.com/advisories/GHSA-776f-qx25-q3cc)

1. Instructions for testing:

1. Closes Issues: #<number> (if appropriate)
#1024

1. [x] Updated meaningful TSDoc to methods including Parameters and Returns, see [Documentation Guide](https://esri.github.io/hub-components/storybook/?path=/story/guides-documentation--page)

1. [x] used semantic commit messages
  
1. [x] PR title follows semantic commit format (**CRITICAL** if the title is not in a semantic format, the release automation will not run!)

1. [x] updated `peerDependencies` as needed. **CRITICAL** our automated release system can **not** be counted on to update `peerDependencies` so we _must_ do it manually in our PRs when needed. See the [updating peerDependencies](/RELEASE.md#Updating-peerDependencies) section of the release instructions for more details.

### CODE REVIEW

**Review by tomwayson — CHANGES_REQUESTED** [review]
@MikeTschudi 

Thanks for this. We'd need to verify that none of the [breaking changes introduced in 4.0 and it's betas](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/CHANGELOG.md) affect how this library is used in hub.js. Running unit tests is not sufficient, b/c we probably stub fast-xml-parser. We'd need to actually call `fetchContent()` w/ an item id that has metadata XML and ensure that it was correctly converted to JSON. I don't think we have an e2e test set up yet that does this, so we'd have to either add one, or at least run it from the command line and verify.

Also, we should remove the changes to the root package.json. If you do that, I can work on the e2e test.

**Comment by MikeTschudi** [comment]
Removed root changes. This seems to produce a confusing dual state for fast-xml-parser:  part old version, part new version.

**Comment by tomwayson** [comment]
Also, it looks like the unit tests did fail: 

image

It looks like part of the breaking change is that the parser is invoked with a new signature: 

https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/2.XMLparseOptions.md

So our code and tests would need to be updated accordingly from:

```ts
const { parse } = await import("fast-xml-parser");
....
return parse(metadataXml, opts);

```

To something like:

```ts
const { XMLParser } = await import("fast-xml-parser");
....
const parser = new XMLParser(opts);
return parser.parse(metadataXml);
```

And again, we'd need to verify that there aren't other breaking changes in the options and/or what it returns.

**Comment by tomwayson** [comment]
After @MikeTschudi and I looked into this a bit further, it turns out that the library w/ the vulnerability, `xml2js` is not even installed. For whatever reason, `fast-xml-parser` just [uses "xml2js" as the name of executable](https://github.com/NaturalIntelligence/fast-xml-parser/blob/v3.20.3/package.json#L18-L20) in it's [package.bin](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#bin) so that it's CLI can be called at the command line.

Closing this for now.

**Comment by olga-knyazeva** [comment]
@tomwayson @MikeTschudi thank you for looking into this. I just want to clarify one thing: our vulnerability scan complains about `fast-xml-parser` itself, not xml2js. And as far as I can see [here](https://github.com/advisories/GHSA-x3cc-x39p-42qx) the `fast-xml-parser` below 4.1.2 has a vulnerability and still needs an upgrade.  Am I missing something?

**Comment by tomwayson** [comment]
thank you @olga-knyazeva 

I've re-opened the original ticket

**Pull request closed without merging**
