### PR TITLE
feat: add ChannelFilter type to discussions

### PR DESCRIPTION
**Pull request by rweber-esri**
1. Description:
Adds a new `ChannelFilter` enum to `@esri/hub-discussions` that will be used to filter searches for posts to those that the current user has one or more posts.

1. Instructions for testing:
Non functional

1. Closes Issues: [2262](https://devtopia.esri.com/dc/hub/issues/2262)

1. [ ] ran commit script (`npm run c`)
Used semantic release commit syntax

_Note_ If you don't run the commit script at least once, the Semantic Pull Request check will fail. Save yourself some time, and run `npm run c` and follow the prompts.

For more information see the README

### CODE REVIEW

**Comment by jersteve** [comment]
The new enum `ChannelFilter` looks great. Why are all the other enums being changed from number to string?

**Comment by rweber-esri** [comment]
> The new enum `ChannelFilter` looks great. Why are all the other enums being changed from number to string?

@jersteve if I'm understanding things correctly, the `type` defined in the other enum's comments were incorrect. All those enum values are of type `string` not `number`, right?

**Comment by jersteve** [comment]
@rweber-esri Sorry, I should have understood from the context what was going on. Yes, you're correct. All of those enums are of type string. Just weird that all of them were of type number before, not sure why that was the case.

**Review by jersteve — APPROVED** [review]
Great job!

**Review by tannerjt — APPROVED** [review]
LGTM, although I wonder why `package-lock.json` has diffs.  Without any changes to `package.json` dependencies, I wouldn't have expected to see any changes to the lock file.

**Pull request merged**
