### PR TITLE
F/collection updates

### PR DESCRIPTION
**Pull request by tomwayson**
Addresses https://github.com/Esri/hub.js/issues/355#issuecomment-697946638 and https://github.com/Esri/hub.js/issues/355#issuecomment-700923580.

@drspacemanphd note that f06bff0 will change the behavior of any search code that calls `encodeAgoQuery()`.

### CODE REVIEW

**Review by drewctate — COMMENTED** [review]
So... these types just won't come back under the map facet on `/search`? If that's the case, I don't really have an opinion.

**Comment by tomwayson** [comment]
Well I would guess that search results in the app would not be affected b/c we group maps and apps together: 

https://hub.arcgis.com/search?collection=App%2CMap

But that's why I want @drspacemanphd to vet this.

**Comment by drewctate** [comment]
Good point @tomwayson .

**Comment by drspacemanphd** [comment]
This makes sense to me, given that App & Map are queried together as part of both Search and Content Library. I've approved

**Review by drspacemanphd — APPROVED** [review]

**Pull request merged**
