### PR TITLE
Add fetch of summary-statistic-card dependencies

### PR DESCRIPTION
**Pull request by MikeTschudi**
so that the dependencies will go into the Solution and will thus be constructed before the Hub Site Application is constructed.

affects @esri/sites

### CODE REVIEW

**Review by drewctate — APPROVED** [review]
Nice catch.

**Comment by MikeTschudi** [comment]
@drewctate, @tomwayson, would you kindly merge this PR?

**Comment by tomwayson** [comment]
@MikeTschudi 

Merged. Do you need me to cut a release? If so it looks like this is a patch, right?

**Comment by MikeTschudi** [comment]
@tomwayson, thank you--a release would be great!  It's a patch for supporting Hub Site Processors in solution.js.

**Comment by tomwayson** [comment]
this has been released in https://github.com/Esri/hub.js/releases/tag/v6.12.1

**Pull request merged**
